### ISSUE TITLE
 slackeventsapi.server.SlackEventAdapterException: Invalid request signature

### ISSUE THREAD

**Issue by vigneshp826** [slackapi/python-slack-events-api#35]
### Description

My App was working well using events API so far, but today i got this error " slackeventsapi.server.SlackEventAdapterException: Invalid request signature". I know that somewhere i messed up something but not able figure out . what could be the reason for this issue?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version:
python version:
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by shanedewael** [comment]
Hey there 👋- the last release contained an update that forces you to use request signing for verification. As a developer, this means that you need to pass in your signing secret rather than the verification token you're likely passing in now. You can find your app's signing secret right above the verification token on the app configuration page under the "Basic Info" tab:

![image](https://user-images.githubusercontent.com/3411005/44275940-f939a280-a1fa-11e8-9093-0f736893956f.png)

If you still have issues after updating your token, let me know 😄

P.S. if you're interested, you can read more about request signing [on our API site](https://api.slack.com/docs/verifying-requests-from-slack).

**Comment by vigneshp826** [comment]
@shanedewael Thank you very much for your quick reply. I will test it out and update you shortly.

**Comment by vigneshp826** [comment]
Thanks @shanedewael . Its working perfect now. Appreciate your help :)

**Comment by Roach** [comment]
Glad to hear it! 🎉
