### ISSUE TITLE
Is it possible to use Tornado?

### ISSUE THREAD

**Issue by itsdkey** [slackapi/python-slack-events-api#63]
### Description

Hi there, I'm writing an issue because I can't connect with the slack workspace that is at the end of the README (Need help? Join Slack Community and talk to us in #slack-api). I've created an account but it still says that it isn't part of the workspace.

So to my question. Is it possible to use Tornado instead of Flask with this package? I want to create a mini app using slackclient + Tornado. I have an HTTP slack app.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@itsdkey Hello, thanks for asking a question! This module tightly depends on Flash, so that it's not possible to use it with other frameworks. The Slack team is planning to provide a new server-side framework that offers a framework-agnostic layer like Bolt for JS's `App` interface. Until then, please consider implementing event receivers with Tornado on your own.

**Comment by itsdkey** [comment]
Okay, thanks for the answer :)
