### ISSUE TITLE
Question about the current state of verification token and proper usage of signing secret

### ISSUE THREAD

**Issue by rcsrao** [slackapi/python-slack-events-api#80]
I see the below notification at https://api.slack.com/authentication/verifying-requests-from-slack

**Verification token deprecation**
We'll continue allowing apps to use verification tokens for now. However, we will retire them completely in coming months. We strongly recommend switching to request signing as soon as possible.

Do we have any other alternative to verify whether requests from SLack are authentic?

**Comment by lavabyrd** [comment]
Hey @rcsrao , its actually on that page you linked. It's using "Signed Secrets" instead. This is in the Readme for this SDK at https://github.com/slackapi/python-slack-events-api#--usage

**Comment by rcsrao** [comment]
@lavabyrd What about incoming messages validations if we just use Flask with REST APIs (Not SDKs)

**Comment by lavabyrd** [comment]
The requests will still contain the Signing secrets, you'll just need to figure out how to handle it in Flask yourself 

I'd suggest having a look at either they existing Python Slack SDK [here](https://github.com/SlackAPI/python-slackclient)

Or the updated one which is currently in beta [Bolt-Python](https://github.com/slackapi/bolt-python)

Outside of that, you may be best reaching out to Slack Support using `/feedback` in any Slack client or by emailing support@slack.com. 

The Github is more used for issues with the SDKs themselves rather than general troubleshooting/questions

**Comment by rcsrao** [comment]
We are currently validating it with signing secret as follows,
```
signing_secret vs request.headers['X-Slack-Signature']
```

I am worried about this method and would like to know about the validity.

**Comment by seratch** [comment]
@rcsrao We recommend using `slack. signature. SignatureVerifier` that `slackclient` PyPI package offers.

```python
from flask import Flask, request, make_response
app = Flask(__name__)

from slack.signature import SignatureVerifier
signature_verifier = SignatureVerifier(os.environ["SLACK_SIGNING_SECRET"])

@app.route("/slack/events", methods=["POST"])
def handler():
    if not signature_verifier.is_valid_request(request.get_data(), request.headers):
        return make_response("invalid request", 403)

    # do something here
```

If you do not want to rely on the dependency for some reason, feel free to reuse the code as it's an open source under the MIT license. https://github.com/slackapi/python-slackclient/blob/v2.9.2/slack/signature/verifier.py

**Comment by seratch** [comment]
Let us know if you have anything further to ask/discuss here. I will close this issue after waiting for your response for a few days.
